require("config.vim-plug")
require("config.luasnip")
require("config.tagbar")
require("config.nerdcommenter")
require("config.catppuccin-theme")
require("config.tele_scope")
require("config.barbar")
-- require("config.vima_git")
require("config.git")
require("config.git_gutter")
require("config.set")
require("config.lsp")
require("config.nvim_tree")
require("config.toggle_term")
require("config.mason_nvim_dap")
require("config.nvim_dap")
require("config.nvim_dap_ui")
