require("config.vim-plug")
require("config.luasnip")
require("config.tagbar")
require("config.nerdcommenter")
require("config.catppuccin-theme")
-- require("config.vima_git")
require("config.git")
require("config.git_gutter")
require("config.set")
require("config.lsp")
