vim.keymap.set("n", "<Leader>db", ":DapToggleBreakpoint<CR>", {})
vim.keymap.set("n", "<Leader>dn", ":DapStepOver<CR>", {})
vim.keymap.set("n", "<Leader>di", ":DapStepInto<CR>", {})
vim.keymap.set("n", "<Leader>do", ":DapStepOut<CR>", {})
vim.keymap.set("n", "<Leader>dc", ":DapContinue<CR>", {})
vim.keymap.set("n", "<Leader>dt", ":DapTerminate<CR>", {})
